import type {
  Conversation, WhatsAppUser, ActivityLog, BotConfig, AnalyticsData
} from "@/types";

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_1",
    userId: "user_1",
    userName: "Jean Pierre",
    phone: "+50912345678",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
    lastMessage: "Can you generate a futuristic city at night?",
    lastMessageTime: new Date(Date.now() - 2 * 60 * 1000),
    messageCount: 34,
    language: "ht",
    isOnline: true,
    commandsUsed: ["/ai", "/image", "/code"],
    messages: [
      { id: "m1", role: "user", content: "Bonjou! Ki jan ou rele?", timestamp: new Date(Date.now() - 20 * 60000), command: "text" },
      { id: "m2", role: "bot", content: "Bonjou! Mwen rele Dawinix AI 🤖 — asistan AI ou nan WhatsApp. Mwen ka ede ou avèk kesyon, kòd, ak imaj. Kijan mwen ka ede ou jodi a?", timestamp: new Date(Date.now() - 19 * 60000) },
      { id: "m3", role: "user", content: "/ai What is quantum computing?", timestamp: new Date(Date.now() - 15 * 60000), command: "/ai" },
      { id: "m4", role: "bot", content: "Quantum computing is a type of computation that uses quantum mechanical phenomena like superposition and entanglement to process information. Unlike classical computers that use bits (0 or 1), quantum computers use qubits that can exist in multiple states simultaneously — enabling them to solve certain problems exponentially faster than traditional computers.\n\n🔬 Key concepts:\n• **Superposition** — a qubit can be 0, 1, or both at once\n• **Entanglement** — qubits can be linked across distance\n• **Interference** — amplify correct answers, cancel wrong ones\n\nApplications: cryptography, drug discovery, optimization, AI.", timestamp: new Date(Date.now() - 14 * 60000) },
      { id: "m5", role: "user", content: "/code Write a Python function to reverse a string", timestamp: new Date(Date.now() - 10 * 60000), command: "/code" },
      { id: "m6", role: "bot", content: "Here's a Python function to reverse a string:\n\n```python\ndef reverse_string(s: str) -> str:\n    \"\"\"\n    Reverses a given string.\n    \n    Args:\n        s: The input string\n    Returns:\n        The reversed string\n    \"\"\"\n    return s[::-1]\n\n# Examples:\nprint(reverse_string(\"Hello\"))     # → olleH\nprint(reverse_string(\"Dawinix\"))   # → xiniwaDprint(reverse_string(\"\"))         # → (empty)\n```\n\n💡 **How it works:** `s[::-1]` uses Python slice notation with step -1, reading the string backwards from end to start. It's the most Pythonic and efficient approach — O(n) time complexity.", timestamp: new Date(Date.now() - 9 * 60000) },
      { id: "m7", role: "user", content: "/image Create a futuristic city at night with neon lights", timestamp: new Date(Date.now() - 5 * 60000), command: "/image" },
      { id: "m8", role: "bot", content: "🎨 Generating your image...\n\n✅ Image created! Here's your futuristic neon city at night:", timestamp: new Date(Date.now() - 4 * 60000), imageUrl: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=600&h=400&fit=crop" },
      { id: "m9", role: "user", content: "Can you generate a futuristic city at night?", timestamp: new Date(Date.now() - 2 * 60000), command: "/image" },
    ],
  },
  {
    id: "conv_2",
    userId: "user_2",
    userName: "Marie Dubois",
    phone: "+33612345678",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face",
    lastMessage: "Merci! Tu es très utile 😊",
    lastMessageTime: new Date(Date.now() - 18 * 60 * 1000),
    messageCount: 21,
    language: "fr",
    isOnline: false,
    commandsUsed: ["/ai", "/code"],
    messages: [
      { id: "m1", role: "user", content: "/ai Explique-moi comment fonctionne l'IA", timestamp: new Date(Date.now() - 40 * 60000), command: "/ai" },
      { id: "m2", role: "bot", content: "L'intelligence artificielle (IA) est un ensemble de techniques permettant aux machines d'imiter des comportements humains tels que l'apprentissage, le raisonnement et la prise de décision.\n\n🧠 **Les grands types d'IA :**\n• **Machine Learning** — les algorithmes apprennent à partir de données\n• **Deep Learning** — réseaux de neurones à plusieurs couches\n• **NLP** — traitement du langage naturel (comme moi!)\n• **Vision par ordinateur** — reconnaissance d'images\n\nJe suis moi-même un modèle de langage (LLM) entraîné sur des milliards de textes pour comprendre et générer du langage naturel.", timestamp: new Date(Date.now() - 39 * 60000) },
      { id: "m3", role: "user", content: "/code Crée une fonction JavaScript pour calculer la suite de Fibonacci", timestamp: new Date(Date.now() - 30 * 60000), command: "/code" },
      { id: "m4", role: "bot", content: "```javascript\n// Fibonacci avec mémoïsation (très efficace)\nfunction fibonacci(n, memo = {}) {\n  if (n in memo) return memo[n];\n  if (n <= 1) return n;\n  memo[n] = fibonacci(n - 1, memo) + fibonacci(n - 2, memo);\n  return memo[n];\n}\n\n// Exemples:\nconsole.log(fibonacci(10)); // 55\nconsole.log(fibonacci(20)); // 6765\nconsole.log(fibonacci(50)); // 12586269025\n```\n\n⚡ Cette version utilise la mémoïsation pour éviter les calculs redondants — O(n) au lieu de O(2ⁿ)!", timestamp: new Date(Date.now() - 29 * 60000) },
      { id: "m5", role: "user", content: "Merci! Tu es très utile 😊", timestamp: new Date(Date.now() - 18 * 60000), command: "text" },
      { id: "m6", role: "bot", content: "Avec plaisir! 😊 Je suis là pour vous aider à tout moment. N'hésitez pas à revenir avec d'autres questions!", timestamp: new Date(Date.now() - 17 * 60000) },
    ],
  },
  {
    id: "conv_3",
    userId: "user_3",
    userName: "Alex Johnson",
    phone: "+12125551234",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face",
    lastMessage: "/code Fix this Node.js error: Cannot read properties of undefined",
    lastMessageTime: new Date(Date.now() - 35 * 60 * 1000),
    messageCount: 58,
    language: "en",
    isOnline: true,
    commandsUsed: ["/ai", "/code", "/image", "/help"],
    messages: [
      { id: "m1", role: "user", content: "/code Fix this Node.js error: Cannot read properties of undefined (reading 'data')", timestamp: new Date(Date.now() - 40 * 60000), command: "/code" },
      { id: "m2", role: "bot", content: "This error means you're trying to access `.data` on something that is `undefined`. Here's how to fix it:\n\n```javascript\n// ❌ BUGGY CODE (what you probably have)\nconst result = await fetchData();\nconsole.log(result.data.users); // Error if result is undefined!\n\n// ✅ FIX 1: Optional chaining (modern JS)\nconst users = result?.data?.users ?? [];\n\n// ✅ FIX 2: Check before access\nif (result && result.data) {\n  console.log(result.data.users);\n}\n\n// ✅ FIX 3: Try-catch with proper error handling\ntry {\n  const response = await fetchData();\n  if (!response || !response.data) {\n    throw new Error('Invalid response structure');\n  }\n  return response.data;\n} catch (error) {\n  console.error('Fetch failed:', error.message);\n  return null;\n}\n```\n\n🔍 **Root cause:** Your async function likely returns `undefined` when an error occurs silently. Always validate API responses!", timestamp: new Date(Date.now() - 39 * 60000) },
      { id: "m3", role: "user", content: "/code Fix this Node.js error: Cannot read properties of undefined", timestamp: new Date(Date.now() - 35 * 60000), command: "/code" },
    ],
  },
  {
    id: "conv_4",
    userId: "user_4",
    userName: "Sophia Chen",
    phone: "+8613912345678",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&h=80&fit=crop&crop=face",
    lastMessage: "Generate an image of a peaceful Japanese garden",
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    messageCount: 12,
    language: "en",
    isOnline: false,
    commandsUsed: ["/image", "/ai"],
    messages: [
      { id: "m1", role: "user", content: "/image Generate a peaceful Japanese garden with cherry blossoms", timestamp: new Date(Date.now() - 130 * 60000), command: "/image" },
      { id: "m2", role: "bot", content: "🎨 Generating your image...\n\n✅ Here's your peaceful Japanese garden:", timestamp: new Date(Date.now() - 129 * 60000), imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&h=400&fit=crop" },
      { id: "m3", role: "user", content: "Generate an image of a peaceful Japanese garden", timestamp: new Date(Date.now() - 120 * 60000), command: "/image" },
    ],
  },
  {
    id: "conv_5",
    userId: "user_5",
    userName: "Carlos Rivera",
    phone: "+5215512345678",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
    lastMessage: "/help",
    lastMessageTime: new Date(Date.now() - 5 * 60 * 60 * 1000),
    messageCount: 5,
    language: "en",
    isOnline: false,
    commandsUsed: ["/help", "/start"],
    messages: [
      { id: "m1", role: "user", content: "/start", timestamp: new Date(Date.now() - 310 * 60000), command: "/start" },
      { id: "m2", role: "bot", content: "👋 Welcome to **Dawinix AI** — your intelligent WhatsApp assistant!\n\n🤖 I can help you with:\n• 💬 `/ai` — Ask me anything\n• 💻 `/code` — Generate or debug code\n• 🎨 `/image` — Create AI-generated images\n• ❓ `/help` — Show all commands\n\nJust type a command or ask me anything in natural language. Let's get started!", timestamp: new Date(Date.now() - 309 * 60000) },
      { id: "m3", role: "user", content: "/help", timestamp: new Date(Date.now() - 300 * 60000), command: "/help" },
      { id: "m4", role: "bot", content: "📋 **Dawinix AI — Command Reference**\n\n`/ai [question]` — Ask any question, get smart answers\n`/code [description]` — Generate code in Python, JS, Node.js, HTML/CSS\n`/image [prompt]` — Generate AI images from text descriptions\n`/start` — Welcome message & introduction\n`/help` — Show this command list\n\n💡 **Tips:**\n• You can also just type naturally without commands!\n• I support English, French, and Haitian Creole\n• I remember your conversation context", timestamp: new Date(Date.now() - 299 * 60000) },
      { id: "m5", role: "user", content: "/help", timestamp: new Date(Date.now() - 5 * 3600000), command: "/help" },
    ],
  },
];

export const MOCK_USERS: WhatsAppUser[] = [
  {
    id: "user_1",
    name: "Jean Pierre",
    phone: "+50912345678",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
    status: "active",
    firstSeen: new Date(Date.now() - 7 * 86400000),
    lastSeen: new Date(Date.now() - 2 * 60000),
    totalMessages: 34,
    commandsUsed: 18,
    language: "ht",
    rateLimit: 45,
    memoryEnabled: true,
  },
  {
    id: "user_2",
    name: "Marie Dubois",
    phone: "+33612345678",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face",
    status: "idle",
    firstSeen: new Date(Date.now() - 14 * 86400000),
    lastSeen: new Date(Date.now() - 18 * 60000),
    totalMessages: 21,
    commandsUsed: 9,
    language: "fr",
    rateLimit: 50,
    memoryEnabled: true,
  },
  {
    id: "user_3",
    name: "Alex Johnson",
    phone: "+12125551234",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face",
    status: "active",
    firstSeen: new Date(Date.now() - 3 * 86400000),
    lastSeen: new Date(Date.now() - 35 * 60000),
    totalMessages: 58,
    commandsUsed: 31,
    language: "en",
    rateLimit: 22,
    memoryEnabled: true,
  },
  {
    id: "user_4",
    name: "Sophia Chen",
    phone: "+8613912345678",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&h=80&fit=crop&crop=face",
    status: "idle",
    firstSeen: new Date(Date.now() - 2 * 86400000),
    lastSeen: new Date(Date.now() - 2 * 3600000),
    totalMessages: 12,
    commandsUsed: 5,
    language: "en",
    rateLimit: 50,
    memoryEnabled: false,
  },
  {
    id: "user_5",
    name: "Carlos Rivera",
    phone: "+5215512345678",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
    status: "idle",
    firstSeen: new Date(Date.now() - 5 * 86400000),
    lastSeen: new Date(Date.now() - 5 * 3600000),
    totalMessages: 5,
    commandsUsed: 3,
    language: "en",
    rateLimit: 50,
    memoryEnabled: false,
  },
  {
    id: "user_6",
    name: "Blocked User",
    phone: "+19995559999",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=80&h=80&fit=crop&crop=face",
    status: "blocked",
    firstSeen: new Date(Date.now() - 20 * 86400000),
    lastSeen: new Date(Date.now() - 10 * 86400000),
    totalMessages: 102,
    commandsUsed: 2,
    language: "en",
    rateLimit: 0,
    memoryEnabled: false,
  },
];

export const MOCK_ACTIVITY: ActivityLog[] = [
  { id: "a1", type: "message", message: "New message from Jean Pierre (+509•••678)", timestamp: new Date(Date.now() - 2 * 60000), severity: "info" },
  { id: "a2", type: "command", message: "/image command executed by Jean Pierre — image generated successfully", timestamp: new Date(Date.now() - 4 * 60000), severity: "success" },
  { id: "a3", type: "webhook", message: "Webhook POST received — message processed in 312ms", timestamp: new Date(Date.now() - 5 * 60000), severity: "success" },
  { id: "a4", type: "command", message: "/code command executed by Alex Johnson — Node.js bug fix generated", timestamp: new Date(Date.now() - 36 * 60000), severity: "success" },
  { id: "a5", type: "error", message: "Rate limit reached for user +999•••999 — request blocked", timestamp: new Date(Date.now() - 50 * 60000), severity: "warning" },
  { id: "a6", type: "message", message: "New message from Marie Dubois (+336•••678)", timestamp: new Date(Date.now() - 18 * 60000), severity: "info" },
  { id: "a7", type: "webhook", message: "Webhook GET verification successful — Meta handshake complete", timestamp: new Date(Date.now() - 2 * 3600000), severity: "success" },
  { id: "a8", type: "error", message: "AI model timeout — fallback response sent (attempt 1/3)", timestamp: new Date(Date.now() - 3 * 3600000), severity: "error" },
  { id: "a9", type: "config", message: "Bot configuration updated — system prompt changed", timestamp: new Date(Date.now() - 6 * 3600000), severity: "info" },
  { id: "a10", type: "command", message: "/ai command executed by Sophia Chen — quantum computing explained", timestamp: new Date(Date.now() - 130 * 60000), severity: "success" },
];

export const DEFAULT_BOT_CONFIG: BotConfig = {
  phoneNumberId: "123456789012345",
  accessToken: "EAAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  webhookVerifyToken: "dawinix_verify_2025",
  webhookUrl: "https://your-server.com/webhook",
  aiModel: "gpt-4o",
  imageModel: "dall-e-3",
  maxContextMessages: 10,
  rateLimit: 50,
  enabledCommands: ["/ai", "/code", "/image", "/help", "/start"],
  supportedLanguages: ["en", "fr", "ht"],
  systemPrompt: "You are Dawinix AI, a smart and friendly WhatsApp assistant. You can answer questions, generate code, explain concepts, and create images. You support English, French, and Haitian Creole. Always be helpful, concise, and accurate.",
  botName: "Dawinix AI",
  fallbackMessage: "Sorry, I couldn't process your request right now. Please try again in a moment. 🙏",
};

export const MOCK_ANALYTICS: AnalyticsData[] = [
  { date: "Apr 21", messages: 42, aiCommands: 18, codeCommands: 12, imageCommands: 8, activeUsers: 6 },
  { date: "Apr 22", messages: 67, aiCommands: 28, codeCommands: 19, imageCommands: 11, activeUsers: 9 },
  { date: "Apr 23", messages: 53, aiCommands: 22, codeCommands: 14, imageCommands: 9, activeUsers: 7 },
  { date: "Apr 24", messages: 89, aiCommands: 41, codeCommands: 26, imageCommands: 15, activeUsers: 12 },
  { date: "Apr 25", messages: 114, aiCommands: 55, codeCommands: 32, imageCommands: 18, activeUsers: 16 },
  { date: "Apr 26", messages: 98, aiCommands: 44, codeCommands: 28, imageCommands: 14, activeUsers: 13 },
  { date: "Apr 27", messages: 73, aiCommands: 31, codeCommands: 19, imageCommands: 12, activeUsers: 10 },
];
